### ISSUE TITLE
So Are Planning on fix the mod loader or are you fixing it 

### ISSUE THREAD

**Issue by ItzNotTheMagicOwl** [AstroTechies/AstroModLoader#10]
To me it seems like you guys stop updating this mod loader. I have a lot fun ideas for mods and for the mod loader to make it easier to use

**Comment by konsti219** [comment]
It's not being updated because
1. Nobody really feels like doing it
2. No one originally involved in building the modding ecosystem is modding anymore
3. No one really knows C#

If you are interested in helping (and have Rust experience) please join the modding discord. https://discord.gg/bBqdVYxu4k
